back/src/pong/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("rooms", views.get_rooms),
]

back/src/transcendance/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("django_prometheus.urls")),
    path('user/', include("user.urls")),
    path('rooms/', include("rooms.urls")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
            settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/src/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
        path("", views.index, name="index"),
        path("account/<int:user_id>/", views.account_view, name="view"),
        path("account/<int:user_id>/edit/", views.edit_account_view, name="edit"),
        path("auth42/", views.auth42, name="auth42"),
        path("friend_list/<int:user_id>/", views.friend_list_view, name="friend-list"),
        path("friend_remove/", views.remove_friend, name="remove-friend"),
        path("friend_request/", views.send_friend_request, name="friend-request"),
        path("friend_request/<int:user_id>/", views.friend_requests, name="friend-requests"),
        path("get_is_auth/", views.get_is_auth, name="get-is-auth"),
        path("get_google_login_url/", views.get_google_login_url, name="get-google-login-url"),
        path("accept_friend_request/<int:friend_request_id>/",
             views.accept_friend_request, name="accept-friend-request"),
        path("decline_friend_request/<int:friend_request_id>/",
             views.decline_friend_request, name="decline-friend-request"),
        path("get_csrf_token/", views.get_csrf_token, name="get-csrf-token"),
        path("login/", views.login_view, name="login"),
        path("logout/", views.logout_view, name="logout"),
        path("register/", views.register_user, name="register"),
        path("search/", views.account_search_view, name="search"),

        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
            name='password_change_done'),

        path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
            name='password_change'),

        path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

        path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset/password_reset_confirm.html'
            ), name='password_reset_confirm'),
        path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html', html_email_template_name='password_reset/password_reset_email.html', email_template_name='password_reset/password_reset_email.html'), name='password_reset'),
        path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
        path("<int:user_id>/accept_friend_request/", views.accept_friend_request, name="accept_friend_request"),
        ]

back/src/user/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models import Q

import os


class MyUsersManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have a username")
        user = self.model(
                email=self.normalize_email(email),
                username=username,
                )
        user.set_password(password)
        user.save(using=self._db)
        return (user)


def get_profile_image_filepath(self, filename):
    return ('profile_images/' + str(self.pk) + '/profile_image.png')


def get_default_profile_image():
    return ("profile_images/default_profile_image.png")


def get_default_profile_42_image(self):
    folder_name = f"profile_images/42{self.pk}/"
    return (os.path.join(folder_name, "profile_image.png"))


def get_profile_image_filepath_42(instance, filename):
    return (os.path.join('profile_image', '42', f'{instance.pk}', filename))


class   Users(AbstractBaseUser):
    first_name          = models.CharField(max_length=64)
    last_name           = models.CharField(max_length=64)
    birth_date          = models.DateTimeField(default = timezone.now)
    username            = models.CharField(max_length=64, unique=True)
    email               = models.EmailField(max_length=100, verbose_name="email", unique=True)
    created_date_time   = models.DateTimeField(verbose_name="date created", auto_now_add=True)
    last_login          = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_active           = models.BooleanField(default=True)
    profile_image = models.FileField(max_length=500, upload_to=get_profile_image_filepath, null=True, blank=True, default=get_default_profile_image)
    friends             = models.ManyToManyField("Users", blank=True)
    hide_email          = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []
    # profile_image       = models.ImageField(max_length=500, upload_to=get_profile_image_filepath, null=True, blank=True, default=get_default_profile_image)

    objects = MyUsersManager()

    def __str__(self):
        return (f"{self.username}")

    # This function substrates the name of the image from the user profile
    # image and sets it as profile_image name
    def get_profile_image_filename(self):
        return (str(self.profile_image)[str(self.profile_image).index(f'profile_images/{self.pk}/'):])


class   OAuth42Users(models.Model):
    login           = models.CharField(max_length=64, unique=True)
    first_name      = models.CharField(max_length=64)
    last_name       = models.CharField(max_length=64)
    email           = models.EmailField(max_length=100,
                                        verbose_name="email", unique=True)
    image = models.FileField(max_length=500,
                             upload_to=get_profile_image_filepath_42,
                             null=True, blank=True)

    def __str__(self):
        return (f"{self.login}")


class FriendList(models.Model):
    user        = models.OneToOneField(
                    settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user")
    friends     = models.ManyToManyField(
                    settings.AUTH_USER_MODEL, blank=True, related_name="user_friends")

    def __str__(self):
        return (f"{self.user.username}")

    def add_friend(self, account):
        """
        Add a new friend.
        If the account is not in our friendlist then we add that friend
        """
        if not account in self.friends.all():
            self.friends.add(account)

    def remove_friend(self, account):
        """
        Remove a friend.
        If the account is in our friendlist then we remove them
        """
        if account in self.friends.all():
            self.friends.remove(account)

    def unfriend(self, removee):
        """
        Initiate the action of unfriending someone.
        """
        remover_friends_list = self  # person terminating the friendship
        # Remove friend from remover friend list
        remover_friends_list.remove_friend(removee)
        # Remove friend from removee friend list
        friends_list = FriendList.objects.get(user=removee)
        friends_list.remove_friend(self.user)

    def is_mutual_friend(self, friend):
        """
        Is this a friend?
        """
        if friend in self.friends.all():
            return (True)
        return (False)


class FriendRequest(models.Model):
    """
    1. Sender
    -- The person sending the friend request
    2. Receiver
    -- The person receiving the friend request
    """
    sender      = models.ForeignKey(
                    settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sender")
    receiver    = models.ForeignKey(
                    settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="receiver")
    is_active   = models.BooleanField(blank=True, null=False, default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (f"{self.sender.username}")

    def accept(self):
        """
        Accept a friend request.
        Update both SENDER and RECEIVER friend lists.
        """

        # Update receiver's friend request status
        receiver_request = FriendRequest.objects.filter(
                Q(sender=self.sender, receiver=self.receiver) |
                Q(sender=self.receiver, receiver=self.sender)
                ).first()
        if receiver_request:
            receiver_request.is_active = False
            receiver_request.save()

        # Update friend lists
        receiver_friend_list = FriendList.objects.get(user=self.receiver)
        if receiver_friend_list:
            receiver_friend_list.add_friend(self.sender)
            sender_friend_list = FriendList.objects.get(user=self.sender)
            if sender_friend_list:
                sender_friend_list.add_friend(self.receiver)
                self.is_active = False
                self.save()

    def decline(self):
        """
        Decline a friend request.
        It is "declined" by setting is_active to False.
        """
        self.is_active = False
        self.save()

    def cancel(self):
        """
        Cancel a friend request.
        This is when the sender decides to cancel their friend request.
        This is only different with respect to "declining" through notification
        is generated.
        """
        self.is_active = False
        self.save()

back/src/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files.base import ContentFile

import logging
import base64

from .models import Users
from .models import OAuth42Users


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=64, help_text='Required. Add a valid email address')

    class Meta:
        model = Users
        fields = ("email", "username", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            user = Users.objects.get(email=email)
        except Exception as e:
            return (email)
        raise forms.ValidationError(f"Email {email} is already in use.")

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = Users.objects.get(username=username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"Username {username} is already in use.")


class UsersAuthentication42Form(UserCreationForm):
    email = forms.EmailField(max_length=64, help_text='Required. Add a valid email address')

    class Meta:
        model = OAuth42Users
        fields = ("email", "login")

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            user = OAuth42Users.objects.get(email=email)
        except Exception as e:
            return (email)
        raise forms.ValidationError(f"Email {email} is already in use.")

    def clean_login(self):
        login = self.cleaned_data['login']
        try:
            user = OAuth42Users.objects.get(login=login)
        except Exception as e:
            return login
        raise forms.ValidationError(f"Login {login} is already in use.")

    def clean(self):
        if self.is_valid():
            login = self.cleaned_data['login']
            if not authenticate(login=login):
                raise forms.ValidationError("Invalid login")


class UsersAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ('username', 'password')

    def clean(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            if not authenticate(username=username, password=password):
                raise forms.ValidationError("Invalid email or password")


class UsersUpdateForm(forms.ModelForm):

    class Meta:
        model = Users
        fields = ('username', 'email', 'profile_image', 'hide_email')

    # def __init__(self, *args, **kwargs):
        # initial = kwargs.get('initial', {})
        # logging.debug("Initial values in init")
        # for field_name, field in self.base_fields.items():
        #    value = initial.get(field_name)
        #    logging.debug(f"{field_name}: {value}")
        # super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        logging.debug(f"email in form: {email}")
        try:
            user = Users.objects.get(email=email)
        except Users.DoesNotExist:
            return email
        raise forms.ValidationError(f"Email {email} is already in use.")

    def clean_username(self):
        username = self.cleaned_data['username']
        logging.debug(f"username in form: {username}")
        try:
            user = Users.objects.get(username=username)
        except Users.DoesNotExist:
            return username
        raise forms.ValidationError(f"Username {username} is already in use.")

    def save(self, commit=True):
        user = super(UsersUpdateForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.hide_email = self.cleaned_data['hide_email']
        user.profile_image = self.cleaned_data['profile_image']
        logging.debug(f"Profile image: {self.cleaned_data['profile_image']}")
        if commit:
            user.save()
        return (user)

back/src/user/templates/user/account.html
{% extends 'user/layout.html' %}
{% load static %}

{% block body %}

<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
	}
	.field-heading{
		color: var(--secondary-text-color);
	}
	.icon-container:hover {
		opacity: 0.3;
		cursor: pointer;
	}
	.friends-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.person-add-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.friend-text{
		font-weight: 500;
		color: black;
	}
	.friends-btn{
		background-color: #cccccc;
		border-color: #cccccc;
		color: #000;
		font-weight: 500;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.card{
		border-radius: 12px;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request{
		color: green;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request{
		color: red;
	}
	.message-btn-text{
		font-weight: 500;
	}
</style>

<div class="container-fluid">
	<div class="d-flex flex-row justify-content-center flex-wrap align-items-start">

		<div class="card profile-card m-2">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="image-container mx-auto mb-4">
		  			<img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image" alt="codingwithmitch logo" id="id_profile_image" src="{{profile_image}}">
		  		</div>
		  		<p class="mt-4 mb-1 field-heading">Email</p>
		  		{%  if is_self %}
		  			<h5>{{email}}</h5>
		  		{% else %}
		  			{% if hide_email %}
			  			<h5>**********</h5>
			  		{% else %}
			  			<h5>{{email}}</h5>
			  		{% endif %}
			  	{% endif %}
		  		<p class="mt-4 mb-1 field-heading">Username</p>
		  		<h5>{{username}}</h5>

		  		<!-- If Auth user is viewing their own profile -->
		  		{% if is_self %}
                <a class="m-auto" href="{% url 'edit' user_id=id %}">Update profile</a>
				<div class="d-flex flex-column mt-4">
					<a class="m-auto" href="{% url 'password_change' %}">Change password</a>
				</div>
		  		{% endif %}
		  	</div>
		  </div>
		</div>

		{% if request.user.is_authenticated %}
		<div class="d-flex flex-column mb-4">

			<!-- THEM to YOU -->
			{% if request_sent == 0 %}
			<div class="card m-2 p-4">
				<div class="d-flex flex-row align-items-center">
					<span class="friend-text align-items-center mr-2">Accept Friend Request</span>
					<span id="id_cancel_{{id}}" class="decline-friend-request material-icons p-1" onclick='triggerDeclineFriendRequest("{{pending_friend_request_id}}")'>cancel</span>
  					<span id="id_confirm_{{id}}" class="confirm-friend-request material-icons p-1" onclick='triggerAcceptFriendRequest("{{pending_friend_request_id}}")'>check</span>
				</div>
			</div>
			{% endif %}

			<div class="card m-2 px-4 pb-4">
				<!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
				{% if is_friend == False and is_self == False %}
						<!-- You sent them a request -->
						{% if request_sent == 1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-danger" id="id_cancel_friend_request_btn">
								Cancel Friend Request
							</button>
						</div>
						{% endif %}
						<!-- No requests have been sent -->
						{% if request_sent == -1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-primary" id="id_send_friend_request_btn">
								Send Friend Request
							</button>
						</div>
						{% endif %}
				{% endif %}

				{% if is_friend %}
					<div class="dropdown pt-4 m-auto">
						<button class="btn btn-secondary dropdown-toggle friends-btn" type="button" id="id_friends_toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Friends
						</button>
						<div class="dropdown-menu" aria-labelledby="id_friends_toggle">
							<a class="dropdown-item" href="#" onclick="removeFriend('{{id}}', onFriendRemoved)">Unfriend</a>
						</div>
					</div>
				{% endif %}
				<!-- Friend list link -->
                <div class="d-flex flex-column pt-4">
                    <a href="#">
                        <div class="d-flex flex-row align-items-center justify-content-center icon-container">
                            <span class="material-icons mr-2 friends-icon">contact_page</span><span class="friend-text">Friends ({{friends|length}})</span>
                        </div>
                    </a>
                    </div>
			</div>

			{#% if friend_requests %#}
			<div class="card m-2 px-4 pb-4">
				<!-- Friend requests -->
		  		<div class="d-flex flex-column pt-4">
                    <a href="#">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="material-icons mr-2 person-add-icon">person_add</span><span class="friend-text">Friend Requests (0)</span>
						</div>
					</a>
				</div>
			</div>
			{#% endif %#}

			{% if is_friend %}
				<div class="d-flex flex-row align-items-center btn btn-primary m-2 px-4" onclick="createOrReturnPrivateChat('{{id}}')">
					<span class="material-icons m-auto">
					message
					</span>
					<span class="message-btn-text m-auto pl-2">Message</span>
				</div>
			{% endif %}

		</div>
		{% endif %}

	</div>
</div>


<script type="text/javascript">

	// called from base_js.html
	//preloadImage("{{profile_image|safe}}", 'id_profile_image')

	function onFriendRequestSent(){
		location.reload();
	}

	function onFriendRequestCancelled(){
		location.reload();
	}

	function onFriendRemoved(){
		location.reload();
	}

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}


	var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
	if (sendFriendRequestBtn != null){
		sendFriendRequestBtn.addEventListener("click", function(){
			sendFriendRequest("{{id}}", onFriendRequestSent)
		})
	}

	var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
	if(cancelFriendRequestBtn != null){
		cancelFriendRequestBtn.addEventListener("click", function(){
			cancelFriendRequest("{{id}}", onFriendRequestCancelled)
		})
	}

	var removeFriendBtn = document.getElementById("id_unfriend_btn")
	if (removeFriendBtn != null){
		removeFriendBtn.addEventListener("click", function(){
			removeFriend("{{id}}", onFriendRemoved)
		})
	}

	function triggerAcceptFriendRequest(friend_request_id){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
</script>

{% endblock body %}

back/src/user/templates/user/edit_account.html
{% extends 'user/layout.html' %}
{% load static %}

{% block body %}


<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
		position: relative;
	}
	.field-heading{
		color: #737373;
	}
	#id_confirm{
		color: green;
	}
	#id_confirm:hover {
		opacity: 0.3;
	}
	#id_cancel:hover {
		opacity: 0.3;
	}
	#id_cancel{
		color: red;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
</style>



<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card profile-card">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="mb-2" id="id_image_crop_confirm">
		  			<span id="id_cancel" class="material-icons">cancel</span>
		  			<span id="id_confirm" class="material-icons">check</span>
		  		</div>
		  		<div class="image-container" id="id_image_container">
	  				<img class="border border-dark rounded-circle img-fluid mx-auto profile-image" id="id_profile_image_display" src="{{form.initial.profile_image.url}}" alt="codingwithmitch logo">
					<div class="middle" id="id_middle_container">
						<div class="text" id="id_text">Edit</div>
					</div>
		  		</div>
		  		<form class="form-signin" method="post" enctype="multipart/form-data">{% csrf_token %}
		  			<input class="d-none" type="file" name="profile_image" id="id_profile_image" onchange="readURL(this)">
			  		<h6 class="mt-4 field-heading">Email</h6>
			  		<input type="email" name="email" id="id_input_email" class="form-control" placeholder="Email address" required autofocus value={{form.initial.email}}>
			  		<h6 class="mt-4 field-heading">Username</h6>
			  		<input type="text" name="username" id="id_input_username" class="form-control" placeholder="Username" required
					value="{{form.initial.username}}">
					<div class="mt-4 checkbox">
						<label>
							<input type="checkbox" name="hide_email" id="id_input_hide_email" {% if form.initial.hide_email %}checked{%endif%}>
							Hide Email
						</label>
					</div>

					{% for field in form %}
					<p>
					{% for error in field.errors %}
					<p style="color: red">{{ error }}</p>
					{% endfor %}
					</p>
					{% endfor %}
					{% if form.non_field_errors %}
					<div style="color: red">
					<p>{{form.non_field_errors}}</p>
					</div>

					{% endif %}

					<div class="d-flex flex-column mt-4">
						<button class="mt-4 btn btn-primary flex-grow-1" type="submit">Save</button>
					</div>
				</form>

		  	</div>
		  </div>
		</div>
	</div>
</div>


<script type="text/javascript">

	var cropper;
	var imageFile;
	var base64ImageString;
	var cropX;
	var cropX;
	var cropWidth;
	var cropHeight;

	enableImageOverlay()

	function enableImageOverlay()
	{
		var text = document.getElementById("id_text")
		text.style.backgroundColor = "#0066ff"
		text.style.color = "white"
		text.style.fontSize = "16px"
		text.style.padding = "16px 32px"
		text.style.cursor = "pointer"

		var profileImage = document.getElementById("id_profile_image")
		profileImage.style.opacity = "1"
		profileImage.style.display = "block"
		profileImage.style.width = "100%"
		profileImage.style.height = "auto"
		profileImage.style.transition = ".5s ease"
		profileImage.style.backfaceVisibility  = "hidden"
		profileImage.style.cursor = "pointer"

		var middleContainer = document.getElementById("id_middle_container")
//		middleContainer.style.transition = ".5s ease"
		middleContainer.style.opacity = "0"
		middleContainer.style.position = "absolute"
		middleContainer.style.top = "50%"
		middleContainer.style.left = "50%"
		middleContainer.style.transform = "translate(-50%, -50%)"
		middleContainer.style.textAlign = "center"

		var imageContainer = document.getElementById("id_image_container")
		imageContainer.addEventListener("mouseover", function( event ) { 
			profileImage.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.addEventListener("mouseout", function( event ) { 
			profileImage.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		imageContainer.addEventListener("click", function(event){
			document.getElementById('id_profile_image').click();
		});

		var cropConfirm = document.getElementById("id_image_crop_confirm")
		cropConfirm.classList.remove("d-flex")
		cropConfirm.classList.remove("flex-row")
		cropConfirm.classList.remove("justify-content-between")
		cropConfirm.classList.add("d-none")
	}

	function disableImageOverlay()
	{
		var profileImage = document.getElementById("id_profile_image_display")
		var middleContainer = document.getElementById("id_middle_container")
		var imageContainer = document.getElementById("id_image_container")
		var text = document.getElementById("id_text")

		imageContainer.removeEventListener("mouseover", function( event ) { 
			profileImage.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.removeEventListener("mouseout", function( event ) { 
			profileImage.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		profileImage.style.opacity = "1"
		middleContainer.style.opacity = "0"
		text.style.cursor = "default"
		text.style.opacity = "0"

		document.getElementById('id_image_container').removeEventListener("click", function(event){
			event.preventDefault();
			// do nothing
		});
		document.getElementById('id_profile_image').addEventListener("click", function(event){
			event.preventDefault();
			// do nothing
		});

		var cropConfirm = document.getElementById("id_image_crop_confirm")
		cropConfirm.classList.remove("d-none")
		cropConfirm.classList.add("d-flex")
		cropConfirm.classList.add("flex-row")
		cropConfirm.classList.add("justify-content-between")

		var confirm = document.getElementById("id_confirm")
		confirm.addEventListener("click", function(event)
		{
			console.log("Sending crop data for processing...")
			cropImage(
				imageFile, 
				cropX, 
				cropY, 
				cropWidth,
				cropHeight
			)
		})

		var cancel = document.getElementById("id_cancel")
		cancel.addEventListener("click", function(event){
			console.log("Reloading window...")
			window.location.reload();
		})content
	}

	/* return null if invalid or base64String if valid */
	function isImageSizeValid(image){
		console.log("max size: {{DATA_UPLOAD_MAX_MEMORY_SIZE}}")
		// console.log(image)
		var startIndex = image.indexOf("base64,") + 7;
		var base64str = image.substr(startIndex);
		var decoded = atob(base64str);
		console.log("FileSize: " + decoded.length);
		if(decoded.length>= "{{DATA_UPLOAD_MAX_MEMORY_SIZE}}"){
			return null
		}
		return base64str
	}

	/*
		Called when a new image is selected from file chooser dialog
	*/
	function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
            	disableImageOverlay()
            	var image = e.target.result
            	var imageField = document.getElementById('id_profile_image_display')
                imageField.src = image
				cropper = new Cropper(imageField, {
					aspectRatio: 1/1,
					crop(event) {
						// console.log("CROP START")
						// console.log("x: " + event.detail.x);
						// console.log("y: " + event.detail.y);
						// console.log("width: " + event.detail.width);
						// console.log("height: " + event.detail.height);
						setImageCropProperties(
							image,
							event.detail.x,
							event.detail.y,
							event.detail.width,
							event.detail.height
						)
					},
				});
            };
            reader.readAsDataURL(input.files[0]);
        }
    };

    function setImageCropProperties(image, x, y, width, height){
		imageFile = image
		cropX = x
		cropY = y
		cropWidth = width
		cropHeight = height
	}

</script>



{% endblock body %}

back/src/user/templates/user/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
        <meta charset="UTF-8">
        <meta name"viewport" content="width=device-width, initial-scale=1.0">
		<title>Users</title>
	</head>
	<body>
        <div class="main">
			<form class="search-bar justify-content-start" onsubmit="return executeQuery();">
			<input type="text" class="form-control" name="q" id="id_q_small" placeholder="Search...">
		</form>
    		{% block body %}
    		{% endblock %}
        </div>
    {% include 'snippets/footer.html' %'}
	</body>
	<script type="text/javascript">
		function executeQuery()
		{
			var query = document.getElementById("id_q_small").value;
			if (query == "")
			{
				query = document.getElementById('id_q_large').value;
			}
			window.location.replace("{% url 'search' %}?q=" + query)
			return false
		}

	</script>
</html>

back/src/user/templates/user/profile.html
{% extends "user/layout.html" %}

{% block body %}

    <h1>Profile</h1>
{% endblock %}

back/src/user/templates/user/send_friend_request.html
{% extends "user/layout.html" %}

{% block body %}
    <ul class="all_users">
        {% for user in users %}
            {% if not user.is_superuser %}
                {% if user not in request.user.friends.all and user != request.user %}
                <h1>{{ user  }} <a href="/send_friend_request/{{ user.id }}">Send Friend Request</a></h1>
                {% endif %}
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

back/src/user/templates/user/user.html
{% extends "user/layout.html" %}

{% block body %}
	<h1>Welcome {{ user.username }}</h1>
	<ul>
		<li>Username: {{ user.username }}</li>
		<li>Email: {{ user.email }}</li>
	</ul>

	<a href="{% url 'logout' %}">Logout</a>
{% endblock body %}